#!/usr/bin/env python3
"""Generate manifest.json for every <mc-version>/<loader>/ category in this repository.

Layout (docs/01.community-config-repo-design.md §4.1):

    <repo-root>/
    ├── <mc-version>/          e.g. 1.20.1/
    │   ├── <loader>/          loader: forge / fabric / neoforge
    │   │   ├── manifest.json  <- (re)generated by this script
    │   │   └── mods/
    │   │       └── <mod_id>.json
    └── ...

Usage:
    python3 generate_manifest.py

For each category the script reads every mods/*.json, extracts mod_id /
mod_name / home_pages from the config content, computes the sha256 of the
raw file bytes, and atomically writes a manifest following the schema in
docs/01.community-config-repo-design.md §5.1. Items are sorted by mod_id.

A manifest is only (re)written when the indexed content changed: if the
new manifest equals the existing one (ignoring the volatile `generated`
timestamp), the existing manifest.json is left untouched.

Exit code: 0 = success, 1 = warnings (files skipped), 2 = fatal error.
"""

import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MANIFEST_NAME = "ControlFlex Community Configs"
SCHEMA_VERSION = 1
MOD_ID_RE = re.compile(r"^[a-z0-9_-]+$")

_warnings = []


def warn(message: str) -> None:
    _warnings.append(message)
    print(f"warning: {message}", file=sys.stderr)


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def discover_categories() -> list[tuple[str, str, Path]]:
    """Find every <mc-version>/<loader>/ directory that contains a mods/ subdir."""
    categories = []
    for version_dir in sorted(p for p in ROOT.iterdir() if p.is_dir()):
        if version_dir.name.startswith("."):
            continue
        for loader_dir in sorted(p for p in version_dir.iterdir() if p.is_dir()):
            if (loader_dir / "mods").is_dir():
                categories.append((version_dir.name, loader_dir.name, loader_dir))
    return categories


def normalize_home_pages(cfg: dict):
    """Return a home_pages list per manifest schema, or None.

    Accepts the config's `home_pages` list as-is (objects or URL strings,
    possibly mixed), or wraps a single `home_page` URL string into a list.
    """
    home_pages = cfg.get("home_pages")
    if isinstance(home_pages, list) and home_pages:
        return home_pages
    home_page = cfg.get("home_page")
    if isinstance(home_page, str) and home_page.startswith(("http://", "https://")):
        return [home_page]
    return None


def build_item(file: Path) -> dict | None:
    """Build one manifest item from a mods/*.json file, or None if it must be skipped."""
    data = file.read_bytes()
    try:
        cfg = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        warn(f"{file}: unreadable JSON, skipping ({exc})")
        return None

    mod_id = cfg.get("mod_id") or file.stem
    if not isinstance(mod_id, str) or not MOD_ID_RE.match(mod_id):
        warn(f"{file}: invalid mod_id {mod_id!r} (expected {MOD_ID_RE.pattern}), skipping")
        return None

    mod_name = cfg.get("mod_name") or mod_id
    if not isinstance(mod_name, str):
        warn(f"{file}: invalid mod_name, falling back to mod_id")
        mod_name = mod_id

    item = {
        "mod_id": mod_id,
        "mod_name": mod_name,
        "path": f"mods/{file.name}",
        "sha256": hashlib.sha256(data).hexdigest(),
    }
    home_pages = normalize_home_pages(cfg)
    if home_pages:
        item["home_pages"] = home_pages
    return item


def generate(category: tuple[str, str, Path]) -> tuple[str, int]:
    """Rebuild the manifest for one category if its content changed.

    Returns (status, item_count); status is "written" or "unchanged".
    """
    version, loader, category_dir = category
    mods_dir = category_dir / "mods"

    items: list[dict] = []
    seen: dict[str, str] = {}
    for file in sorted(mods_dir.glob("*.json")):
        item = build_item(file)
        if item is None:
            continue
        if item["mod_id"] in seen:
            warn(
                f"{category_dir}: duplicate mod_id {item['mod_id']!r} "
                f"(first from {seen[item['mod_id']]}), keeping the first"
            )
            continue
        seen[item["mod_id"]] = item["path"]
        items.append(item)

    items.sort(key=lambda item: item["mod_id"])

    manifest = {
        "schemaVersion": SCHEMA_VERSION,
        "name": MANIFEST_NAME,
        "generated": utc_now(),
        "items": items,
    }
    # Everything except `generated` is deterministic given the mods/ content.
    stable = {key: value for key, value in manifest.items() if key != "generated"}

    manifest_path = category_dir / "manifest.json"
    existing = None
    if manifest_path.exists():
        try:
            existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            warn(f"{manifest_path}: existing manifest is not valid JSON, rewriting ({exc})")
        if existing is not None and not isinstance(existing, dict):
            warn(f"{manifest_path}: existing manifest is not a JSON object, rewriting")
            existing = None

    if existing is not None:
        existing_stable = {key: value for key, value in existing.items() if key != "generated"}
        if existing_stable == stable:
            print(f"{version}/{loader}: unchanged ({len(items)} items), skipping")
            return "unchanged", len(items)

    tmp_path = category_dir / f"manifest.json.tmp{os.getpid()}"
    tmp_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    os.replace(tmp_path, manifest_path)

    print(f"{version}/{loader}: {len(items)} items -> {manifest_path.relative_to(ROOT)}")
    return "written", len(items)


def main() -> int:
    categories = discover_categories()
    if not categories:
        print(f"error: no <mc-version>/<loader>/mods/ categories found under {ROOT}", file=sys.stderr)
        return 2

    results = [generate(category) for category in categories]
    written = sum(status == "written" for status, _ in results)
    total = sum(count for _, count in results)
    print(
        f"\nDone: {written} written, {len(results) - written} unchanged, {total} items"
        + (f", {len(_warnings)} warning(s) — see stderr" if _warnings else "")
    )
    return 1 if _warnings else 0


if __name__ == "__main__":
    sys.exit(main())
